# assumption: Travis build runs in bash 4.0 (or greater)

language: python

before_script:
  - chmod +x *.sh
  - pip install json-spec

script:
  - ./xmlvalidator.sh
  - ./jsonvalidator.sh

notifications:
  email: false
